stages:
  data_ingestion:
    cmd: python laptop_project/pipeline/data_ingestion_pipeline.py
    deps:
      - laptop_project/pipeline/data_ingestion_pipeline.py
    outs:
      - artifact/data_ingestion/feature_store/laptop.csv
      - artifact/data_ingestion/ingested/train.csv
      - artifact/data_ingestion/ingested/test.csv


  data_validation:
    cmd: python laptop_project/pipeline/data_validation_pipeline.py
    deps:
      - laptop_project/pipeline/data_validation_pipeline.py
    outs:
      - artifact/data_validation/drift_report/report.yaml
      

  data_transformation:
    cmd: python laptop_project/pipeline/data_transformation_pipeline.py
    deps:
      - laptop_project/pipeline/data_transformation_pipeline.py
    outs:
      - artifact/data_transformation/transformed/train.npy
      - artifact/data_transformation/transformed/test.npy
      - artifact/data_transformation/transformed_object/preprocessing.pkl

  model_training:
    cmd: python laptop_project/pipeline/model_trainer_pipeline.py
    deps:
      - laptop_project/pipeline/model_trainer_pipeline.py
    outs:
      - artifact/model_trainer/trained_model/model.pkl

  model_evaluation:
    cmd: python laptop_project/pipeline/model_evaluation_pipeline.py
    deps:
    - laptop_project/pipeline/model_evaluation_pipeline.py
    # outs:
    #   - artifact/model_evaluation/evaluation_report.json

  # training:
  #   cmd: python src/cnnClassifier/pipeline/stage_03_model_trainer.py
  #   deps:
  #     - src/cnnClassifier/pipeline/stage_03_model_trainer.py
  #     - config/config.yaml
  #     - artifacts/data_ingestion/Chest-CT-Scan-data
  #     - artifacts/prepare_base_model
  #   params:
  #     - IMAGE_SIZE
  #     - EPOCHS
  #     - BATCH_SIZE
  #     - AUGMENTATION
  #   outs:
  #     - artifacts/training/model.h5


  # evaluation:
  #   cmd: python src/cnnClassifier/pipeline/stage_04_model_evaluation.py
  #   deps:
  #     - src/cnnClassifier/pipeline/stage_04_model_evaluation.py
  #     - config/config.yaml
  #     - artifacts/data_ingestion/Chest-CT-Scan-data
  #     - artifacts/training/model.h5
  #   params:
  #     - IMAGE_SIZE
  #     - BATCH_SIZE
  #   metrics:
  #   - scores.json:
  #       cache: false